# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]

# Permalinks
permalink:        pretty

# Setup
title:            The Overfitter
tagline:          'Big Data, Cloud, Apache Spark, Hadoop, Blogging, AWS'
url:              https://jijosg.github.io/
shorturl:         jijosg.github.io

author:
  name:           'Jijo Sunny George'
  url:            https://twitter.com/jijo_sunny

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/jijosg/jijosg.github.io
  
# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate
