title: The Overfitter
author:
  name: Jijo Sunny George
  email: jijosunny90@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Big Data, Cloud, Apache Spark, Hadoop, Blogging, AWS
show_excerpts: true # set to true to show excerpts on the homepage
permalink: pretty

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: classic
  # generate social links in footer
  social_links:
    twitter: jijo_sunny
    github:  jijosg
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: jijo-sunny-george-62476027
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
theme: minima

tagline:          'Big Data, Cloud, Apache Spark, Hadoop, Blogging, AWS'
url:              https://jijosg.github.io/
shorturl:         jijosg.github.io

plugins:
 - jekyll-feed
 - jekyll-seo-tag

disqus:
  shortname: https-jijosg-github-io

google_analytics: UA-167436539-1
